---
- name: Install package from an installation link on Windows Server
  hosts: windows
  tasks:
    - name: Download package from the link
      win_get_url:
        url: http://10.22.21.172:8081/share/KcsSetup.exe  # Replace with the actual package URL
        dest: C:\temp\  # Destination where the package will be downloaded
      register: download_result

    - name: Install the downloaded package
      ##win_command: msiexec.exe /i C:\Users\Administrator\Downloads\KcsSetup.exe /qn  # Modify the installation command as needed
      ##win_command: C:\Users\Administrator\Downloads\KcsSetup.exe
      win_package:
       path: C:\temp\KcsSetup.exe
       state: present